### ISSUE TITLE
Support the features such as matplotlib's colormap

### ISSUE THREAD

**Issue by mrkn** [red-data-tools/red-colors#2]
Adding the features like `ListedColormap` and `LinearSegmentedColormap` in matplotlib.

**Comment by nanobowers** [comment]
Hi @mrkn , I have been looking at this and was wondering if it is reasonable to have this feature (matplotlib ListedColormap and LinearSegmentedColormap) depend on Numo::NArray?  Currently this gem does not depend on Numo::NArray and all matrix manipulation is done with standard ruby Arrays

**Comment by mrkn** [comment]
This issue is related to Charty.  Could you please wait I will return for work on Charty?

**Comment by mrkn** [comment]
> Currently this gem does not depend on Numo::NArray and all matrix manipulation is done with standard ruby Arrays

There is a history about numo-narray dependency of this library.

This library first depended on numo-narray and JRuby wasn't supported.
At that time we used numo-narray only for 3x3 matrix multiplication for color space conversion.
We decided that we should quit to use numo-narray so that we can support JRuby because 3x3 matrix multiplication is not a heavy operation.

If we need to use a heavy linear algebraic operation in this library or there are other reasons to depend on numo-narray, we can use numo-narray optionally [as red-palette does](https://github.com/red-data-tools/red-palette/blob/master/lib/palette/helper.rb).

**Comment by mrkn** [comment]
@nanobowers do you perhaps need this feature soon?

**Comment by nanobowers** [comment]
@mrkn I had intended to work on the heatmap function of unicode_plots.rb, and I believe there is somewhat of a dependency on this colormap feature, so I thought to try working on it myself because I saw this "mrkn removed their assignment on Oct 15, 2019".  But there is no rush, I am contributing to be helpful and continue to learn Ruby, not because of an immediate need.

As you may know, the matplotlib source is a very heavy user of numpy and conversion of that colormap code is much more straightforward using Numo::NArray than it would be to re-write using standard ruby Arrays - especially in cases where 2D arrays are used.  As you mention, i don't think there is so much matrix manipulation as to be a big performance issue using standard ruby arrays, but it will be more difficult to translate and to patch any code the more it deviates from matplotlib, if compatibility is an important goal.

Thanks for the explanation and history of this package, it was helpful in trying to understand your design goal.
